# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: java-saml CI with Maven

on: [push, pull_request, workflow_dispatch]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11' ]
        os: [ 'blacksmith-2vcpu-ubuntu-2204' ]
    name: Java ${{ matrix.Java }} (${{ matrix.os }})
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: useblacksmith/setup-java@v5
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - name: Maven Test
      run: mvn --batch-mode clean verify org.jacoco:jacoco-maven-plugin:report
